//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Lotos.BinbinDomainLanguage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "binbinddddsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"BinbinDomainLanguage";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Com.Lotos";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID BinbinDomainLanguageDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(BinbinDomainLanguageCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID BinbinDomainLanguageExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(BinbinDomainLanguageCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewBinbinDomainLanguageExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(BinbinDomainLanguageCommandSetId), 0x0001);
	
		// Package identifier
		public const string BinbinDomainLanguagePackageId = "26e42182-9b3f-4454-9c6b-7dd99a96a13d";
		
		// Editor factory identifier
		public const string BinbinDomainLanguageEditorFactoryId = "dd877174-46bc-4ac7-b203-df0b9f8543df";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string BinbinDomainLanguageModelExplorerToolWindowId = "be15d4bc-8f48-4aab-a869-adb359c6c677";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Com.Lotos.BinbinDomainLanguage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string BinbinDomainLanguageCommandSetId = "dfb34c07-ec1d-477b-be2f-c63cef686e14";
	}
}